services:
  g_tg_dev_app:
    container_name: "g_tg_dev_app"
    restart: "always"
    build:
      context: ..
      dockerfile: ../Dockerfile
    environment:
      - TZ=Europe/Moscow
      - NODE_ENV=development
      - PORT=4000
      - HOST=0.0.0.0
      - TELEGRAM_USERNAME=${TELEGRAM_USERNAME:?err}
      - TELEGRAM_NAME=${TELEGRAM_NAME:?err}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:?err}
      - USERS_ADMIN=${USERS_ADMIN:?err}
      - DATABASE_URL=${DATABASE_URL:?err}
    ports:
      - "4000:4000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - :/src
      - /node_modules
      - ./logs:/logs
    command: yarn start:dev
    extra_hosts:
